try {
  sayHello('Welcome');
} catch (err) {
  console.log('Error:', err.message);
}
